### ISSUE TITLE
Discourse forum

### ISSUE THREAD

**Issue by hkdobrev** [algolia/awesome-algolia#10]
I'm not sure in which section this should be added, but I think the Discourse forum for Algolia community should be added in this list- https://discourse.algolia.com/

It is strangely missing from this page as well: https://community.algolia.com/

**Comment by rayrutjes** [comment]
Good catch @hkdobrev ,

I submitted a PR. I'll wait for @dzello to review it as I'm not sure if I put it in the right place ;)

**Comment by dzello** [comment]
Thanks @hkdobrev! Great catch and it's coming to the community site soon ;)

Placement LGTM @rayrutjes 👍
