### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by fabrizim** [algolia/awesome-algolia#35]
What is the status of the woocommerce plugin? The [documentation is public](https://community.algolia.com/woocommerce/quick-start.html), but [the repository that it refers to](https://github.com/algolia/algoliasearch-woocommerce/) is not publically available. Is this project still active?

**Comment by rayrutjes** [comment]
Hi @fabrizim ,

The plugin you are mentioning is till in private Beta.

We hope to have more news to share soon.

**Comment by fabrizim** [comment]
Cool - glad to hear as it looks like a great addition. If you are looking for testing / contributing I'd be happy to help.

**Comment by rayrutjes** [comment]
Can you drop me a line at support@algolia.com?

**Comment by fabrizim** [comment]
Will do
