### ISSUE TITLE
Dead link in project description

### ISSUE THREAD

**Issue by green-coder** [algolia/awesome-algolia#38]
![screen shot 2018-06-25 at 7 01 58 pm](https://user-images.githubusercontent.com/598193/41846810-85463470-78aa-11e8-907a-313bb0601eda.png)

The link https://algolia.com/awesome goes to:

![screen shot 2018-06-25 at 7 02 41 pm](https://user-images.githubusercontent.com/598193/41846818-874cc1da-78aa-11e8-9d02-da564a99b8b0.png)

**Comment by Haroenv** [comment]
The link was supposed to go to this project, @vvo do you remember where this was configured?

**Comment by vvo** [comment]
No but do we actually need it?

**Comment by vvo** [comment]
Removed the link, thx!
