### ISSUE TITLE
Dead link in list

### ISSUE THREAD

**Issue by cperdigou** [algolia/awesome-algolia#7]
Just a quick heads-up about a dead link in your list!
![screen shot 2017-01-06 at 15 55 42](https://cloud.githubusercontent.com/assets/19646768/21721451/c50ca616-d428-11e6-95ec-2adcb40c7518.png)

Both demo and code are 404

**Comment by rayrutjes** [comment]
Wow, thanks a lot for spotting that one @cperdigou ❤️ 
It is now fixed ;)
